use UndiciMaggio;

create table Clienti (
	id INT,
	nome VARCHAR(50),
	cognome VARCHAR(50),
	email VARCHAR(50),
	eta INT,
	citta VARCHAR(50)
);
insert into Clienti (id, nome, cognome, email, eta, citta) values (1, 'Andy', 'Tabbernor', 'atabbernor0@ca.gov', 83, 'Baratleke');
insert into Clienti (id, nome, cognome, email, eta, citta) values (2, 'Theodore', 'Esposi', 'tesposi1@squarespace.com', 75, 'Haozhai');
insert into Clienti (id, nome, cognome, email, eta, citta) values (3, 'Cicely', 'Humphries', 'chumphries2@wikia.com', 43, 'Didou');
insert into Clienti (id, nome, cognome, email, eta, citta) values (4, 'Milton', 'Bride', 'mbride3@baidu.com', 73, 'Krajan Sumberanget');
insert into Clienti (id, nome, cognome, email, eta, citta) values (5, 'Doyle', 'Paolo', 'dpaolo4@shinystat.com', 89, 'Konstantynów Łódzki');
insert into Clienti (id, nome, cognome, email, eta, citta) values (6, 'Ozzy', 'Kloska', 'okloska5@senate.gov', 43, 'Grati Satu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (7, 'Kaylil', 'Cod', 'kcod6@geocities.jp', 23, 'Sarāvān');
insert into Clienti (id, nome, cognome, email, eta, citta) values (8, 'Celinda', 'Goundrill', 'cgoundrill7@slashdot.org', 21, 'Siva');
insert into Clienti (id, nome, cognome, email, eta, citta) values (9, 'Emmet', 'Simpson', 'esimpson8@china.com.cn', 63, 'Vannes');
insert into Clienti (id, nome, cognome, email, eta, citta) values (10, 'Hyacinthe', 'Jardein', 'hjardein9@arizona.edu', 64, 'Hujiaying');
insert into Clienti (id, nome, cognome, email, eta, citta) values (11, 'Ax', 'Espinho', 'aespinhoa@ucla.edu', 89, 'Pingle');
insert into Clienti (id, nome, cognome, email, eta, citta) values (12, 'Hildagarde', 'Cowle', 'hcowleb@globo.com', 96, 'Alunda');
insert into Clienti (id, nome, cognome, email, eta, citta) values (13, 'Hymie', 'Awton', 'hawtonc@psu.edu', 36, 'Sélestat');
insert into Clienti (id, nome, cognome, email, eta, citta) values (14, 'Page', 'Bottrell', 'pbottrelld@wisc.edu', 44, 'Sishan');
insert into Clienti (id, nome, cognome, email, eta, citta) values (15, 'Courtnay', 'Ruste', 'crustee@edublogs.org', 49, 'Khayr Kōṯ');
insert into Clienti (id, nome, cognome, email, eta, citta) values (16, 'Nikkie', 'Border', 'nborderf@tinypic.com', 46, 'Nahariya');
insert into Clienti (id, nome, cognome, email, eta, citta) values (17, 'Tracy', 'Crutch', 'tcrutchg@cnn.com', 31, 'Bęczarka');
insert into Clienti (id, nome, cognome, email, eta, citta) values (18, 'Sharity', 'Pescud', 'spescudh@wikispaces.com', 56, 'Nuevo Chamelecón');
insert into Clienti (id, nome, cognome, email, eta, citta) values (19, 'Jessika', 'Lengthorn', 'jlengthorni@shinystat.com', 65, 'Miskolc');
insert into Clienti (id, nome, cognome, email, eta, citta) values (20, 'Martynne', 'Bolan', 'mbolanj@de.vu', 85, 'Bergen');
insert into Clienti (id, nome, cognome, email, eta, citta) values (21, 'Sheffy', 'Peaple', 'speaplek@liveinternet.ru', 30, 'Cunén');
insert into Clienti (id, nome, cognome, email, eta, citta) values (22, 'Masha', 'Lowres', 'mlowresl@com.com', 26, 'Sharm el-Sheikh');
insert into Clienti (id, nome, cognome, email, eta, citta) values (23, 'Sondra', 'Goodsal', 'sgoodsalm@google.it', 34, 'Blokdesa Situgede');
insert into Clienti (id, nome, cognome, email, eta, citta) values (24, 'Barbi', 'Tyrone', 'btyronen@google.nl', 53, 'Pertunmaa');
insert into Clienti (id, nome, cognome, email, eta, citta) values (25, 'Karrie', 'Pach', 'kpacho@soundcloud.com', 80, 'Caxarias');
insert into Clienti (id, nome, cognome, email, eta, citta) values (26, 'Josepha', 'Eustice', 'jeusticep@latimes.com', 43, 'Jalālpur');
insert into Clienti (id, nome, cognome, email, eta, citta) values (27, 'Biddy', 'Startin', 'bstartinq@globo.com', 78, 'Los Fresnos');
insert into Clienti (id, nome, cognome, email, eta, citta) values (28, 'Vivianna', 'Chatelet', 'vchateletr@toplist.cz', 57, 'Iwakuni');
insert into Clienti (id, nome, cognome, email, eta, citta) values (29, 'Alain', 'Tart', 'atarts@youku.com', 83, 'Mantes-la-Jolie');
insert into Clienti (id, nome, cognome, email, eta, citta) values (30, 'Cecily', 'Hame', 'chamet@yelp.com', 86, 'Longjumeau');
insert into Clienti (id, nome, cognome, email, eta, citta) values (31, 'Glynnis', 'Hunstone', 'ghunstoneu@whitehouse.gov', 91, 'Sibayo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (32, 'Micky', 'Renneke', 'mrennekev@google.es', 97, 'Gore');
insert into Clienti (id, nome, cognome, email, eta, citta) values (33, 'Carlyn', 'Keel', 'ckeelw@wordpress.com', 88, 'Non Sung');
insert into Clienti (id, nome, cognome, email, eta, citta) values (34, 'Hazlett', 'Stump', 'hstumpx@rakuten.co.jp', 73, 'Savé');
insert into Clienti (id, nome, cognome, email, eta, citta) values (35, 'Trueman', 'Birkwood', 'tbirkwoody@merriam-webster.com', 63, 'Aranguren');
insert into Clienti (id, nome, cognome, email, eta, citta) values (36, 'Baxie', 'Canedo', 'bcanedoz@mashable.com', 60, 'Penteado');
insert into Clienti (id, nome, cognome, email, eta, citta) values (37, 'Cynthie', 'Elijah', 'celijah10@newyorker.com', 34, 'Ōgaki');
insert into Clienti (id, nome, cognome, email, eta, citta) values (38, 'Anson', 'Flude', 'aflude11@shinystat.com', 86, 'Shtip');
insert into Clienti (id, nome, cognome, email, eta, citta) values (39, 'Lucienne', 'Rowlett', 'lrowlett12@artisteer.com', 93, 'Nagu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (40, 'Nevins', 'Fann', 'nfann13@smugmug.com', 42, 'Caijiapu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (41, 'Faith', 'Bradshaw', 'fbradshaw14@pagesperso-orange.fr', 64, 'Chinchero');
insert into Clienti (id, nome, cognome, email, eta, citta) values (42, 'Gayle', 'Stenett', 'gstenett15@technorati.com', 47, 'Sonorejo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (43, 'Demetris', 'Ditchfield', 'dditchfield16@dmoz.org', 51, 'Towa');
insert into Clienti (id, nome, cognome, email, eta, citta) values (44, 'Hermon', 'Pettingill', 'hpettingill17@senate.gov', 94, 'Rudnichnyy');
insert into Clienti (id, nome, cognome, email, eta, citta) values (45, 'Charisse', 'Badman', 'cbadman18@gmpg.org', 42, 'Bairro Assunção Piedade');
insert into Clienti (id, nome, cognome, email, eta, citta) values (46, 'Ivar', 'McKerrow', 'imckerrow19@unicef.org', 65, 'Quilo-quilo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (47, 'Chane', 'Sheal', 'csheal1a@mit.edu', 79, 'Peuhaq');
insert into Clienti (id, nome, cognome, email, eta, citta) values (48, 'Nedi', 'Hartzog', 'nhartzog1b@cbc.ca', 54, 'Villa Santa Rita');
insert into Clienti (id, nome, cognome, email, eta, citta) values (49, 'Crysta', 'Cundy', 'ccundy1c@craigslist.org', 29, 'Malšice');
insert into Clienti (id, nome, cognome, email, eta, citta) values (50, 'Tonya', 'Kenryd', 'tkenryd1d@163.com', 93, 'Hannover');
insert into Clienti (id, nome, cognome, email, eta, citta) values (51, 'Debee', 'Hexum', 'dhexum1e@time.com', 61, 'Wulong');
insert into Clienti (id, nome, cognome, email, eta, citta) values (52, 'Filberte', 'Beynon', 'fbeynon1f@disqus.com', 96, 'Rancaseneng');
insert into Clienti (id, nome, cognome, email, eta, citta) values (53, 'Branden', 'MacAlroy', 'bmacalroy1g@netscape.com', 29, 'Mežica');
insert into Clienti (id, nome, cognome, email, eta, citta) values (54, 'Adeline', 'Margrem', 'amargrem1h@ask.com', 26, 'Sumber Tengah');
insert into Clienti (id, nome, cognome, email, eta, citta) values (55, 'Currey', 'Hardingham', 'chardingham1i@google.ca', 27, 'Obispos');
insert into Clienti (id, nome, cognome, email, eta, citta) values (56, 'Abigael', 'Kingscote', 'akingscote1j@altervista.org', 75, 'Lindome');
insert into Clienti (id, nome, cognome, email, eta, citta) values (57, 'Wendi', 'Neads', 'wneads1k@sciencedaily.com', 64, 'Mochudi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (58, 'Ruby', 'Storks', 'rstorks1l@bloglovin.com', 70, 'Šmarje pri Jelšah');
insert into Clienti (id, nome, cognome, email, eta, citta) values (59, 'Kaile', 'Chasemoore', 'kchasemoore1m@seattletimes.com', 64, 'Mafang');
insert into Clienti (id, nome, cognome, email, eta, citta) values (60, 'Jorrie', 'Huntriss', 'jhuntriss1n@eventbrite.com', 48, 'Bongao');
insert into Clienti (id, nome, cognome, email, eta, citta) values (61, 'Joelle', 'Beesley', 'jbeesley1o@xrea.com', 78, 'Pertunmaa');
insert into Clienti (id, nome, cognome, email, eta, citta) values (62, 'Carrissa', 'Castellini', 'ccastellini1p@amazonaws.com', 74, 'Oslo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (63, 'Bette', 'Spillman', 'bspillman1q@hibu.com', 71, 'Polzela');
insert into Clienti (id, nome, cognome, email, eta, citta) values (64, 'Read', 'Ciccerale', 'rciccerale1r@jigsy.com', 29, 'Lankaran');
insert into Clienti (id, nome, cognome, email, eta, citta) values (65, 'Helena', 'Sizzey', 'hsizzey1s@twitpic.com', 18, 'Göteborg');
insert into Clienti (id, nome, cognome, email, eta, citta) values (66, 'Ingar', 'Lintill', 'ilintill1t@wp.com', 89, 'Nevyts’ke');
insert into Clienti (id, nome, cognome, email, eta, citta) values (67, 'Sharl', 'Bollans', 'sbollans1u@furl.net', 68, 'Itatinga');
insert into Clienti (id, nome, cognome, email, eta, citta) values (68, 'Lynn', 'D''Ambrogi', 'ldambrogi1v@prnewswire.com', 39, 'Cikadu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (69, 'Estel', 'Leggis', 'eleggis1w@umich.edu', 37, 'Atlantis');
insert into Clienti (id, nome, cognome, email, eta, citta) values (70, 'Yankee', 'Pes', 'ypes1x@apache.org', 97, 'Ghouazi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (71, 'Jenn', 'Upson', 'jupson1y@ustream.tv', 18, 'Novodmitriyevskaya');
insert into Clienti (id, nome, cognome, email, eta, citta) values (72, 'Phyllys', 'Heckney', 'pheckney1z@cnbc.com', 77, 'Kolomyya');
insert into Clienti (id, nome, cognome, email, eta, citta) values (73, 'Prisca', 'Denson', 'pdenson20@chronoengine.com', 86, 'Caleufú');
insert into Clienti (id, nome, cognome, email, eta, citta) values (74, 'Leigh', 'Talby', 'ltalby21@fotki.com', 80, 'Nan');
insert into Clienti (id, nome, cognome, email, eta, citta) values (75, 'Pat', 'Robilart', 'probilart22@wordpress.com', 81, 'Chexi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (76, 'Dorie', 'Minett', 'dminett23@latimes.com', 72, 'Ozubulu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (77, 'Patty', 'Huntriss', 'phuntriss24@etsy.com', 97, 'Würzburg');
insert into Clienti (id, nome, cognome, email, eta, citta) values (78, 'Brinna', 'Cattach', 'bcattach25@sourceforge.net', 45, 'Solnechnoye');
insert into Clienti (id, nome, cognome, email, eta, citta) values (79, 'Nigel', 'Lindsey', 'nlindsey26@privacy.gov.au', 65, 'Vranje');
insert into Clienti (id, nome, cognome, email, eta, citta) values (80, 'Reuven', 'Balogun', 'rbalogun27@nhs.uk', 42, 'Ulcinj');
insert into Clienti (id, nome, cognome, email, eta, citta) values (81, 'Paule', 'Balsdone', 'pbalsdone28@huffingtonpost.com', 71, 'Älvdalen');
insert into Clienti (id, nome, cognome, email, eta, citta) values (82, 'Arabele', 'Jacobowitz', 'ajacobowitz29@deliciousdays.com', 80, 'Guanjiabao');
insert into Clienti (id, nome, cognome, email, eta, citta) values (83, 'Evaleen', 'Rainer', 'erainer2a@cnbc.com', 65, 'Chorente');
insert into Clienti (id, nome, cognome, email, eta, citta) values (84, 'Mady', 'Moyles', 'mmoyles2b@japanpost.jp', 93, 'Sinargalih');
insert into Clienti (id, nome, cognome, email, eta, citta) values (85, 'Ami', 'Iacoboni', 'aiacoboni2c@cnbc.com', 36, 'Kommunisticheskiy');
insert into Clienti (id, nome, cognome, email, eta, citta) values (86, 'Gilbertine', 'Yerborn', 'gyerborn2d@umich.edu', 79, 'Lagodekhi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (87, 'Felita', 'Lewtey', 'flewtey2e@weebly.com', 80, 'Shnogh');
insert into Clienti (id, nome, cognome, email, eta, citta) values (88, 'Cora', 'Benes', 'cbenes2f@angelfire.com', 74, 'Vyaz’ma');
insert into Clienti (id, nome, cognome, email, eta, citta) values (89, 'Nicolis', 'Meiningen', 'nmeiningen2g@independent.co.uk', 81, 'Gramoteino');
insert into Clienti (id, nome, cognome, email, eta, citta) values (90, 'Claudell', 'Disman', 'cdisman2h@foxnews.com', 86, 'Gorodets');
insert into Clienti (id, nome, cognome, email, eta, citta) values (91, 'Zonda', 'Hamley', 'zhamley2i@independent.co.uk', 29, 'Tétouan');
insert into Clienti (id, nome, cognome, email, eta, citta) values (92, 'Philippine', 'Orchart', 'porchart2j@xinhuanet.com', 89, 'Santo Estêvão');
insert into Clienti (id, nome, cognome, email, eta, citta) values (93, 'Maia', 'Kurth', 'mkurth2k@huffingtonpost.com', 78, 'Timon');
insert into Clienti (id, nome, cognome, email, eta, citta) values (94, 'Kate', 'Hawken', 'khawken2l@joomla.org', 75, 'Buk');
insert into Clienti (id, nome, cognome, email, eta, citta) values (95, 'Horton', 'Rozenbaum', 'hrozenbaum2m@sina.com.cn', 63, 'Kista');
insert into Clienti (id, nome, cognome, email, eta, citta) values (96, 'Sharron', 'Calafato', 'scalafato2n@de.vu', 43, 'Liebu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (97, 'Arnie', 'Sandars', 'asandars2o@ustream.tv', 38, 'Hevlín');
insert into Clienti (id, nome, cognome, email, eta, citta) values (98, 'Corrie', 'Geach', 'cgeach2p@fc2.com', 50, 'Fengsheng');
insert into Clienti (id, nome, cognome, email, eta, citta) values (99, 'Jefferson', 'Fattorini', 'jfattorini2q@psu.edu', 73, 'Aktogay');
insert into Clienti (id, nome, cognome, email, eta, citta) values (100, 'Nona', 'Hedau', 'nhedau2r@ocn.ne.jp', 83, 'Jamaica');
